### ISSUE TITLE
分别统计每个账号的流量情况

### ISSUE THREAD

**Issue by sola614** [sprov065/sprov-ui#10]
就是一个服务器有多个账号，想知道每个账号分别用了多少流量，不知道可不可以加这个功能

**Comment by sprov065** [comment]
未来大概会加上

**Comment by twq168** [comment]
可以增加一个设置端口连接数的功能吗？

**Comment by sprov065** [comment]
> 可以增加一个设置端口连接数的功能吗？

不可以，因为 v2ray 官方不支持这个功能。

**Comment by twq168** [comment]
那增加一个时间管理可以吗？比如对每个端口一个月有效或一年有效或半年，增加端口的时间，这样给别人开通也清楚是开通了多久的

**Comment by twq168** [comment]
> > 可以增加一个设置端口连接数的功能吗？
> 
> 不可以，因为v2ray官方不支持这个功能。

那增加一个时间管理可以吗？比如对每个端口一个月有效或一年有效或半年，增加端口的时间，这样给别人开通也清楚是开通了多久的

**Comment by sprov065** [comment]
> > > 可以增加一个设置端口连接数的功能吗？
> > 
> > 
> > 不可以，因为v2ray官方不支持这个功能。
> 
> 那增加一个时间管理可以吗？比如对每个端口一个月有效或一年有效或半年，增加端口的时间，这样给别人开通也清楚是开通了多久的

这个功能在计划中
