### ISSUE TITLE
可否在配置中默认写入禁止不安全的加密

### ISSUE THREAD

**Issue by jimmygiven** [sprov065/sprov-ui#11]
禁止none和aes-128-cfb的加密方式的连接，能否默认写入config呢？以防手误选错加密方式   
  "disableInsecureEncryption": true

**Comment by sprov065** [comment]
这个完全可以自行保证，就一个选项的事，万一又有小白说连不上，又是我的面板的锅。。。

**Comment by jimmygiven** [comment]
其实这种情况也基本不会发生，因为拿到二维码或者链接基本就不会改参数了，就怕真有脑子不好使的去自己乱改，我真遇见过。tcp改kcp的

**Comment by jimmygiven** [comment]
也行吧，手动写一下config也不算太麻烦
