### ISSUE TITLE
帐号列表页设置层叠按钮

### ISSUE THREAD

**Issue by jimmygiven** [sprov065/sprov-ui#12]
账号列表页每个用户的信息可以折叠起来，显示一些主要信息如端口、备注、流量，协议、ID、加密方式等折叠，可以有效提升管理效率。

非常喜欢这个web面板，美观且实用，2月的时候就想找这么一个多用户管理面板没找到，然后就学会了读写config 2333
给开发者一个大大的👍

**Comment by sprov065** [comment]
这样即使折叠起来显示的信息还是很多，你可以使用账号搜索功能

**Comment by jimmygiven** [comment]
对啊，我把搜索给忽略了，你一说我才想起那块还有个搜索
