### ISSUE TITLE
请教关于ws+http+tls

### ISSUE THREAD

**Issue by Bigdragon532** [sprov065/sprov-ui#13]
你好，
今天很幸运的看到了这款面板，非常感谢。从网上了解到目前ws+http+tls的组合方式比较稳定。
花了一上午的时间从谷歌上学习相关信息并实际操作，都以失败告终。
请问能否以sprov-ui为例，给指导一下。

再次感谢开发者为广大谷歌粉带来的帮助和支持。

**Comment by sprov065** [comment]
需要域名和域名对应的ssl证书，把这两个弄好了直接在面板上配置 tls 即可。我可能之后会在博客出相关教程，可以关注一下。

**Comment by Bigdragon532** [comment]
好的，谢谢。
