### ISSUE TITLE
我的流量数据跟实际使用不符，远大于我本身实际使用量

### ISSUE THREAD

**Issue by 1321353970** [sprov065/sprov-ui#14]

**Comment by sprov065** [comment]
请先说明是面板运行状态监控页面显示的系统流量数据还是 v2ray 账号的流量数据。

1、如果是面板运行状态监控页面显示的流量数据，那么有可能是因为统计了系统的内网流量，**请告诉我你的系统版本，以及所有的网卡名称**。

2、v2ray 账号流量应该不会出问题，因为这是 v2ray 自身统计的，面板只是做一下收集，当然也不排除可能是面板的 BUG 引起的，如果是这种情况，那么**请尝试重启面板或者重新安装面板**，如果还是不行，**请详细描述统计的流量差错多少，是否每个账号流量数据都异常**。
