### ISSUE TITLE
v2ray 的状态一直未未运行？重启N次也不生效

### ISSUE THREAD

**Issue by myworksfun** [sprov065/sprov-ui#16]
简短描述所遇到的问题：**怎么重启v2ray 的状态都是“未运行”**
使用的系统：centos7
sprov-ui 状态信息：OK，没问题的。
v2ray 状态信息：未运行
v2ray 配置内容（cat /etc/v2ray/config.json）：
使用的浏览器：Google chrome ver73.
![TIM截图20190423164131](https://user-images.githubusercontent.com/45185967/56567393-6356e280-65e7-11e9-8409-d0b4711e8c8c.png)

**Comment by sprov065** [comment]
使用以下命令检查 v2ray 报错信息，大部分原因都是因为由于你的设置不当导致配置文件内容不符合 v2ray 的要求，从而无法启动。

systemctl status v2ray -l

**Comment by myworksfun** [comment]
> 使用以下命令检查 v2ray 报错信息，大部分原因都是因为由于你的设置不当导致配置文件内容不符合 v2ray 的要求，从而无法启动。
> 
> systemctl status v2ray -l

Thanks author, 重新纯净安装解决了这个问题， V2可以正常运行了。 请问大大，ws+TLS如果能自动配置就好了，已有域名，不会申请诸如lets encrypted 这样的SSL证书，看了你的那些填空，不会玩了。^_^，另外，UI界面不支持手动退出账号吗?
