### ISSUE TITLE
cookies 中的域名mxpnl.net是用来干什么的？ 会通过程序收集用户隐私吗？

### ISSUE THREAD

**Issue by myworksfun** [sprov065/sprov-ui#18]
cookies 中的域名mxpnl.net是用来干什么的？ 会收面板程序收集用户隐私吗？
![1](https://user-images.githubusercontent.com/45185967/56637620-a9bb4880-669e-11e9-9910-f696f369fdc8.png)

**Comment by sprov065** [comment]
我没有见过这个域名，我看这个域名也没有解析到任何IP。

我用 Google 稍微搜索了一下，可能的解释是 Chrome 的一些插件引起的，比如广告拦截插件等。具体原因我也不太清楚，但是面板肯定是不会有的。

**Comment by myworksfun** [comment]
> 我没有见过这个域名，我看这个域名也没有解析到任何IP。
> 
> 我用 Google 稍微搜索了一下，可能的解释是 Chrome 的一些插件引起的，比如广告拦截插件等。具体原因我也不太清楚，但是面板肯定是不会有的。

感谢 ，去排查Chrome插件的问题了。
