### ISSUE TITLE
关于ws+nginx+tls的配置问题

### ISSUE THREAD

**Issue by jcx70100** [sprov065/sprov-ui#20]
作者您好，感谢您的作品，为V2ray的配置带来了很大的便利。

之前一直使用的ws+nginx反代+tls的配置，在使用您的可视化面板后，发现一个问题：

nginx通过443端口与外界网络联系，内部通过特定端口（比如1000）来与v2ray联系，那么要实现多用户的话只能是所有用户公用1000端口，可是在使用您的程序时，在设置了第一个用户后，以相同端口添加第二个用户是会提示端口已被使用，因此想请问您一下，有没有办法在使用ws+nginx反代+tls配置的情况下，实现多用户共用一个端口？

**Comment by sprov065** [comment]
面板暂不支持 vmess 单端口多用户的配置，实现起来有许多需要考虑的问题，未来可能会有。

多人用建议还是 tcp 传输，或者自行修改 v2ray 配置文件，只要配置文件符合 v2ray 要求，不会影响到面板。

**Comment by jcx70100** [comment]
好的，感谢
