### ISSUE TITLE
设置好重启服务器后 再也启动不了

### ISSUE THREAD

**Issue by yimshing** [sprov065/sprov-ui#23]
● sprov-ui.service - sprov-ui Service
   Loaded: loaded (/etc/systemd/system/sprov-ui.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-05-09 18:20:16 CST; 1min 22s ago
  Process: 3744 ExecStart=/usr/bin/java -jar /usr/local/sprov-ui/sprov-ui.jar (code=exited, status=1/FAILURE)
 Main PID: 3744 (code=exited, status=1/FAILURE)

May 09 18:20:14 TastyArtistic-VM systemd[1]: Started sprov-ui Service.
May 09 18:20:14 TastyArtistic-VM java[3744]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
May 09 18:20:14 TastyArtistic-VM java[3744]: SLF4J: Defaulting to no-operation (NOP) logger implementation
May 09 18:20:14 TastyArtistic-VM java[3744]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
May 09 18:20:16 TastyArtistic-VM java[3744]: sprov-ui 启动失败：Address already in use
May 09 18:20:16 TastyArtistic-VM systemd[1]: sprov-ui.service: main process exited, code=exited, status=1/FAILURE
May 09 18:20:16 TastyArtistic-VM systemd[1]: Unit sprov-ui.service entered failed state.
May 09 18:20:16 TastyArtistic-VM systemd[1]: sprov-ui.service failed.

**Comment by sprov065** [comment]
Address already in use，面板监听端口被占用，更换一个端口
