### ISSUE TITLE
大佬下个版本可以添加 不同帐号可以用相同端口么?

### ISSUE THREAD

**Issue by logdns** [sprov065/sprov-ui#24]
大佬下个版本可以添加 不同帐号可以用相同端口么?
例如有个V2已经是443端口
 然后再开个帐号443端口 就 会提示 端口 已使用，请填写其它端口

可能这个会影响流量统计功能

**Comment by sprov065** [comment]
会影响流量统计功能，流量统计会统计一个端口的流量，所以使用同一端口的用户的流量都会统计到一块。
这个功能有待考虑。

**Comment by logdns** [comment]
好的,感谢大佬

冒昧问一下大佬.

能不能 新版本 独立 用户,  不用做收费支付哪些,不是盈利方向,

因为偶尔小圈子里面的朋友 使用给他开了独立账户独立端口, 有的人可能需要登录看看
