### ISSUE TITLE
tag标识具体表示什么参数，为何需要唯一性

### ISSUE THREAD

**Issue by Mycheol** [sprov065/sprov-ui#5]
2.0版本就在不同机器上体验了这个面板，突然发现更新了不少版本
重新部署了一遍后发现多了 tag 标识，URL 和二维码等等新的功能
原本2月份时候就打算建议加个链接或者二维码，但是想想作者应该会想到的😂

然后现在我有一些疑问和建议：
1. 添加节点时，最后一行中可以选填的 tag 标识具体表示什么参数？
它的数值为何需要非空或者唯一？tag标志填写有什么注意事项吗？
2. 我解码了生成的 vmess 链接，发现遵循的是 v2ray 的 Windows 图形客户端 
v2rayN 作者设计的 v2.0+的分享链接格式。但是"ps": "remark"为空，当然确实没对其进行设置啦！
所以就想提问能否在后续的版本中增加，添加节点时填入“备注别名”的选项，用以区别不同的节点。

而且，我记得 v2rayN 版本的分享链接的 json 数据格式中并没有前文提到的 tag 类型的键值对。
本身也是设计了备注名的键值对，所以应该也不是像我猜测的这里的 tag 标识是用来备注节点信息的。

希望作者能够解答与采纳，谢谢！

**Comment by Mycheol** [comment]
感谢回答！看到项目更新了，等有时间升级一下试试（主要是想测试一下 vmess 链接还在 Mac 上还报错不😂，当然这个问题不怪您的面板，初步判断应该是应用程序的bug或者说是逻辑缺陷——导入不含备注名称的URL会报错，然后导入失败）

**Comment by sprov065** [comment]
由于我没有Mac设备，所以没有在Mac上的软件进行测试，如果仍然还是不行，请说明是哪个软件，并且把这个软件生成的链接格式告诉我。

**Comment by Mycheol** [comment]
经过多次测试，之前报错确实是 Mac 上的的 V2rayX 自身的问题：我发现问题确实是该程序导入不含备注名称的 URL 会报错，然后导入失败。您更新过后，可以在 URL 中加入 tag 标签的信息当作备注名后，测试了很多次可以正常导入了。感谢您的更新，有问题我会继续反馈的！
