### ISSUE TITLE
远程服务器返回错误: (500) 内部服务器错误。

### ISSUE THREAD

**Issue by eatneko** [sprov065/sprov-ui#7]
v2rayN显示这个错误log，全局和PAC模式（第一个和第二个），都无法正常翻墙。
其他账号如，TG的倒测试成功了

**Comment by sprov065** [comment]
可能是 v2ray 配置文件的问题，请说明一下你添加了什么配置，并把你的配置文件的内容发上来，使用 **cat /etc/v2ray/config.json** 命令查看配置文件的内容。

**Comment by behappy00** [comment]
看到配置文件之后呢，怎末看出哪里出错？
